FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install evaluation-specific dependencies
COPY docker/requirements/requirements-eval.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy logic and artifacts
COPY config.py evaluate.py ./
# COPY model/ ./model/
# COPY data/ ./data/

# Generate visualizations and fairness reports
# Uncomment
CMD ["python", "evaluate.py"]
